#pragma once
#include "SADXStructs.h"
#include "Chaos.h"
void DisablePausee();
void RandomPhysics();
void Nos0und_ForYou();
void UncoupleCamera();
void RandomChaooAnimal();
void RandomChaoo();
void RandomKillMomentum(CharObj2* p1);
void FastAccel(CharObj2* p1);
void RandomVSpeed(CharObj2* p1);
void RandomHSpeed(CharObj2* p1);
void RandomHurt();
void RandomPowerUP(EntityData1* p1);
void MGiantScale(EntityData1* p1);
void RandomTimeOfDay();
void RandomDroppedRings(EntityData1* p1);
void RandomClipLevel();
void RandomPause();
void SwapCamera();
void RandomDebug();
void RandomXGravity();
void RandomYGravity();
void RandomZGravity();
void NoGravity();
void RandomControlDisable();
void MSmallScale(EntityData1* p1);
void AndKnuckles();
void RandomSwapMusic();
void ChaosPlayVoice_rng();
void RandomDPadDownCheck();
void RandomTeleport();
void RandomNoClip();
void InputInvert();
void RandomRotate();
void RingAllergy();
void TeleportRandomTask();
void IncreaseCutsceneSkipTime();
void RemovePowerUp();
void RandomCollisionSize();
void FlipCamera();
void CameraReset();
void SpinCamera();
