#pragma once
#include "SADXStructs.h"
#include "Chaos.h"
extern float OldMaxAccel;
extern float OldAirAccel;
extern float OldHangTime;
extern int CameraSide;
extern int DpadDown;
extern int IssSowboarding;
extern int RandomSpawnAmount;
extern int RingCount;
extern int EVHandyCap;
extern bool BigFishingCheck();
void DisablePausee();
void RandomPhysics();
void Nos0und_ForYou();
void UncoupleCamera();
void RandomChaooAnimal();
void RandomChaoo();
void RandomKillMomentum(playerwk* p1);
void FastAccel(playerwk* p1);
void RandomVSpeed(playerwk* p1);
void RandomHSpeed(playerwk* p1);
void RandomHurt();
void RandomPowerUP(taskwk* p1);
void RandomTimeOfDay();
void RandomDroppedRings(taskwk* p1);
void RandomPause();
void SwapCamera();
void RandomDebug();
void RandomXGravity();
void RandomYGravity();
void RandomZGravity();
void NoGravity();
void RandomControlDisable();
void MSmallScale(taskwk* p1);
void AndKnuckles();
void RandomSwapMusic();
void ChaosPlayVoice_rng();
void RandomDPadDownCheck();
void RandomTeleport();
void RandomNoClip();
void InputInvert();
void RandomRotate();
void RingAllergy();
void TeleportRandomTask();
void IncreaseCutsceneSkipTime();
void RemovePowerUp();
void RandomCollisionSize();
void FlipCamera();
void CameraReset();
void SpinCamera();
void CameraNOP();
void DrunkCamera();
void SideWaysCamera();
void WalkThruWallsNop();
void WalkThruWallsReset();
void BurgerManSpin();
void NewEffect();
void Set_Sonic_Ice();
void EmeraldShardMa();
void RandomKnuxRingSpring(taskwk* p1);