#pragma once
extern bool EggViperHandiCapCheck();
extern uint32_t IlDuce;
void BigRock(taskwk* p1);
void RandomFruit(taskwk* p1);
void RandomHat(taskwk* p1);
void RandomCheckPoint(taskwk* p1);
void RandomSpeedPad(taskwk* p1);
void RandomBurgerMan(taskwk* p1);
void RandomKeyBlock(taskwk* p1);
void RandomSnowboard();
void RandomSpring(taskwk* p1);
void RandomSpikeBall(taskwk* p1);
void RandomEmblem(taskwk* p1);
void RandomFan(taskwk* p1);
void RandomBarrel(taskwk* p1);
bool GrabAbleObjects();
void RandomConveyorBelt(taskwk* p1);
void RandomConveyorStop(taskwk* p1);
void RandomFountain(taskwk* p1);
void RandomTarget(taskwk* p1);
void RandomPopUpTarget(taskwk* p1);