#pragma once
#include "Chaos.h"
void NoClipTimerCheck();
void InputInvertTimerCheck();
void CameraDeattchTimerCheck();
void XYZGravityTimerCheck();
void NoGravityTimerCheck();
void DisableControlTimerCheck();
void DpadDownOrDieTimerCheck();
void ForcePauseTimerCheck();
void SnowBoardTimerCheck();
void FastAccelTimerCheck();
void Nos0und__TimerCheck();
void RingAllergyTimerCheck();
void PauseDisableTimerCheck();
void CustomCameraEffectsTimersCheck();
void DebugTimerCheck();
void AirCraftSpawnerTimerCheck();
void SpinMaTimerCheck();
void CheckAllEffectsTimer();
void ChaosTimer();